name: Build and deploy .NET to Azure Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Global settings you can tweak
env:
  DOTNET_VERSION: '8.0.x'                      # set to 6.0.x or 7.0.x if your app targets that
  AZURE_WEBAPP_NAME: 'REPLACE_WITH_APP_NAME'   # <-- change to your Azure Web App name
  # Optional: If you know the exact project to publish, uncomment the next line and set the path
  # APP_PROJECT_PATH: 'src/MyApp/MyApp.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          pwd
          echo "Top-level files:"
          ls -la
          echo "First 200 lines of recursive listing:"
          ls -R | head -n 200

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true

      - name: Detect solution or project
        id: detect
        shell: bash
        run: |
          set -e
          SOL=$(git ls-files '*.sln' | head -n 1 || true)
          PROJ=$(git ls-files '*.csproj' | head -n 1 || true)
          if [[ -n "$SOL" ]]; then
            echo "found=solution" >> $GITHUB_OUTPUT
            echo "path=$SOL" >> $GITHUB_OUTPUT
            echo "Detected solution: $SOL"
          elif [[ -n "$PROJ" ]]; then
            echo "found=project" >> $GITHUB_OUTPUT
            echo "path=$PROJ" >> $GITHUB_OUTPUT
            echo "Detected project: $PROJ"
          else
            echo "ERROR: No .sln or .csproj found. Make sure your repository contains a .NET solution or project."
            exit 1
          fi

      - name: Restore
        run: dotnet restore "${{ steps.detect.outputs.path }}"

      - name: Build
        run: dotnet build "${{ steps.detect.outputs.path }}" -c Release --no-restore

      - name: Choose app project for publish
        id: publishproj
        shell: bash
        run: |
          set -e
          # If you know your app project, set APP_PROJECT_PATH at the top of this file.
          if [[ -n "${APP_PROJECT_PATH:-}" ]]; then
            echo "path=$APP_PROJECT_PATH" >> $GITHUB_OUTPUT
            echo "Using provided APP_PROJECT_PATH: $APP_PROJECT_PATH"
            exit 0
          fi
          # Prefer a Web SDK project
          for p in $(git ls-files '*.csproj'); do
            if grep -q 'Sdk="Microsoft.NET.Sdk.Web"' "$p"; then
              echo "path=$p" >> $GITHUB_OUTPUT
              echo "Using web project: $p"
              exit 0
            fi
          done
          # Fallback: first project found
          p=$(git ls-files '*.csproj' | head -n 1 || true)
          if [[ -n "$p" ]]; then
            echo "path=$p" >> $GITHUB_OUTPUT
            echo "Fallback publish project: $p"
            exit 0
          fi
          echo "ERROR: No .csproj found for publish."
          exit 1

      - name: Publish to folder
        run: dotnet publish "${{ steps.publishproj.outputs.path }}" -c Release -o "${{ github.workspace }}/publish" --no-build

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{ github.workspace }}/publish

      # --- Deployment to Azure Web App using Publish Profile ---
      # Create a secret named AZURE_WEBAPP_PUBLISH_PROFILE in your repository settings.
      # Get the publish profile from the Azure Portal: Web App -> Get publish profile (Downloads a .PublishSettings file)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ github.workspace }}/publish
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # --- Alternative (commented): OIDC login instead of publish profile ---
      # If you prefer federated credentials, set up a Service Principal with OIDC
      # and provide these three secrets in your repo: AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID.
      # Then uncomment this block and remove 'publish-profile' above.
      #
      # - name: Azure login (OIDC)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: Deploy to Azure Web App (OIDC)
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     package: ${{ github.workspace }}/publish
      #
      # Optional: If you ran into MissingSubscriptionRegistration for Microsoft.AlertsManagement,
      # make sure the subscription has that provider registered once (via Azure Portal or CLI).
